name: ebay-config

# Trading API OAuth - https://developer.ebay.com/api-docs/static/oauth-tokens.html

# UPDATE the values in this file, before running the tests
api.sandbox.ebay.com:
    appid: GKoo-gkoo-SBX-42eb6be68-a9e3aeaa
    certid: SBX-2eb6be68dff1-108e-4863-838c-4e7c
    devid: e63949f3-07f6-4d74-b8e3-1c52d109579a
    redirecturi: <redirect_uri-from-developer-portal>

api.ebay.com:
    appid: GKoo-gkoo-SBX-42eb6be68-a9e3aeaa
    certid: SBX-2eb6be68dff1-108e-4863-838c-4e7c
    devid: e63949f3-07f6-4d74-b8e3-1c52d109579a
    redirecturi: <redirect_uri-from-developer-portal>